### ISSUE TITLE
Adding -swim option

### ISSUE THREAD

**Issue by oalders** [DDvO/GPXConv#4]
Hi @DDvO,

I hope all is well! Open water swimming season has resumed and I have my first set of bad GPS points from my Apple Watch, so I wanted to follow up on a previous comment of yours:

> If you provide me feedback/corrections to the following suggested limit data for swimming:
> 
>     $MIN_TIMEDIFF          = 1;
>     $MAX_SENSIBLE_SPEED    = 10;
>     $MAX_SENSIBLE_ACCEL    = 1;
>     $MAX_SENSIBLE_ELE_GAIN = 1;
>     $MAX_SENSIBLE_ELE_LOSS = 1;
> I can add the -swim option any time.

> $MIN_TIMEDIFF          = 1;

I think this makes sense. Most swimmers will be tracking GPS on a watch, so you'd only get a reading when the arm with the watch exits the water. Having said that, you can also just put a GPS device in a swim buoy and it would be able to get readings much more often. Some people tuck a watch under their cap.

>     $MAX_SENSIBLE_SPEED    = 10;

I just checked some results from a local race that took place today with some very good swimmers. The fastest time for a 1km race came in at 13:26. Based on that, I think `$MAX_SENSIBLE_SPEED    = 6;` should be a sensible default.

>     $MAX_SENSIBLE_ACCEL    = 1;

I think this is good

>     $MAX_SENSIBLE_ELE_GAIN = 1;
>     $MAX_SENSIBLE_ELE_LOSS = 1;

I think those are both reasonable as well. I guess in theory you could be swimming up or downstream, but I think those are not the vast majority of cases.

**Comment by oalders** [comment]
<img width="936" alt="Screenshot 2023-07-02 at 9 53 27 PM" src="https://github.com/DDvO/GPXConv/assets/96205/7e0f5d39-6c87-4a9b-af5d-5b6080a8fbe6">
<img width="936" alt="Screenshot 2023-07-02 at 9 58 05 PM" src="https://github.com/DDvO/GPXConv/assets/96205/454caf2f-6284-43f4-b310-0c4278b04b7f">

**Comment by DDvO** [comment]
Nice to hear from you.
Thank you for your feedback and the PR.
I also like the adaptation regarding `MAX_SENSIBLE_SPEED` for swmming and merged your PR.

**Comment by DDvO** [comment]
> <img alt="Screenshot 2023-07-02 at 9 53 27 PM" width="936" src="https://user-images.githubusercontent.com/96205/250425927-7e0f5d39-6c87-4a9b-af5d-5b6080a8fbe6.png"> <img alt="Screenshot 2023-07-02 at 9 58 05 PM" width="936" src="https://user-images.githubusercontent.com/96205/250425931-454caf2f-6284-43f4-b310-0c4278b04b7f.png">

So this depicts the smoothing done by `gpxconv` using the parameters set by the  new `swim` option?
Very nice demonstration of its effect!

**Comment by oalders** [comment]
> So this depicts the smoothing done by `gpxconv` using the parameters set by the new `swim` option?

That's correct. I did turn down `MAX_SENSIBLE_SPEED` to 2 in this case as that makes more sense for me, but this reduced the swim distance from ~4 km to ~2km. 

There are 3 buoys set up in a triangle. I turn at the buoys and my lines are usually fairly straight, so having the GPS points go off the lines adds a lot of distance that I never covered. There's one small triangle that looks to have been a bigger one which was downsized by the script, but I'm not too concerned about that. I upload my activities to Strava and they don't appear to use any kind of GPS smoothing algorithm, so your work continues to be very helpful to me. 🙏🏻

**Comment by DDvO** [comment]
> I did turn down `MAX_SENSIBLE_SPEED` to 2 in this case as that makes more sense for me, but this reduced the swim distance from ~4 km to ~2km.

This indicates that for `MAX_SENSIBLE_SPEED` the value of 2 is more appropriate than 6.
I just came across some info at https://schwimmlexikon.de/schwimmgeschwindigkeit/ that 
even for race swimmers the velocity over distances of more than 200 m is less than 2 m/s.
So I've adapted the constant this way.

> There are 3 buoys set up in a triangle. I turn at the buoys and my lines are usually fairly straight, so having the GPS points go off the lines adds a lot of distance that I never covered. There's one small triangle that looks to have been a bigger one which was downsized by the script, but I'm not too concerned about that.

It could well be that the upper corner of that triangle got removed for other reasons, such as (apparently) a jump in elevation or a too sharp turn. The script provides diagnostics from which you could find out the actual reason.

Taking into account that even after the smoothing applied, the other lines are not as straight as they should be, I presume that summing up all lengths the total distance is still pretty correct. You likely could confirm this in case you know the circumference of the buoyo triangle.

> I upload my activities to Strava and they don't appear to use any kind of GPS smoothing algorithm, so your work continues to be very helpful to me. 🙏🏻

Very pleased about this!

**Comment by DDvO** [comment]
> I did turn down `MAX_SENSIBLE_SPEED` to 2 in this case as that makes more sense for me, but this reduced the swim distance from ~4 km to ~2km.

This indicates that for `MAX_SENSIBLE_SPEED` the value of 2 is more appropriate than 6.
I found some info at https://schwimmlexikon.de/schwimmgeschwindigkeit/ that 
even for race swimmers the velocity over distances of more than 200 m is less than 2 m/s.
So I've adapted the constant this way.

> There are 3 buoys set up in a triangle. I turn at the buoys and my lines are usually fairly straight, so having the GPS points go off the lines adds a lot of distance that I never covered. There's one small triangle that looks to have been a bigger one which was downsized by the script, but I'm not too concerned about that.

It could well be that the upper corner of that triangle got removed for other reasons, such as an apparent jump in elevation or an apparently too sharp turn. From the warnings printed by the script you could find out the actual reason.

Taking into account that even after the smoothing applied, the other lines are not as straight as they should be, I presume that, summing up all lengths, the total distance is still pretty correct. You likely could confirm this if knowing the circumference of the buoy triangle.

> I upload my activities to Strava and they don't appear to use any kind of GPS smoothing algorithm, so your work continues to be very helpful to me. 🙏🏻

Very pleased about this!

**Comment by oalders** [comment]
> This indicates that for MAX_SENSIBLE_SPEED the value of 2 is more appropriate than 6.
> I just came across some info at https://schwimmlexikon.de/schwimmgeschwindigkeit/ that
> even for race swimmers the velocity over distances of more than 200 m is less than 2 m/s.
> So I've adapted the constant this way.

I'm a bit confused about the units. I thought `MAX_SENSIBLE_SPEED` was in km/h rather than m/s? 2 m/s would be 7.2 km/h.

> It could well be that the upper corner of that triangle got removed for other reasons, such as (apparently) a jump in elevation or a too sharp turn. The script provides diagnostics from which you could find out the actual reason.

Great. I will keep that in mind. I used the script again this weekend and it didn't create any smaller triangles.

> Taking into account that even after the smoothing applied, the other lines are not as straight as they should be, I presume that summing up all lengths the total distance is still pretty correct. You likely could confirm this in case you know the circumference of the buoyo triangle.

The buoys are never set in exactly the same configuration week to week, but from what I can tell the results after smoothing are quite good. 😄

**Comment by DDvO** [comment]
> > This indicates that for MAX_SENSIBLE_SPEED the value of 2 is more appropriate than 6.
> > I just came across some info at https://schwimmlexikon.de/schwimmgeschwindigkeit/ that
> > even for race swimmers the velocity over distances of more than 200 m is less than 2 m/s.
> > So I've adapted the constant this way.
> 
> I'm a bit confused about the units. I thought `MAX_SENSIBLE_SPEED` was in km/h rather than m/s? 2 m/s would be 7.2 km/h.

Ah, right, I confused the units! Thanks for pointing this out.
So I've fixed the value of `MAX_SENSIBLE_SPEED` to be 7 km/h for swimming.

> > It could well be that the upper corner of that triangle got removed for other reasons, such as (apparently) a jump in elevation or a too sharp turn. The script provides diagnostics from which you could find out the actual reason.
> 
> Great. I will keep that in mind. I used the script again this weekend and it didn't create any smaller triangles.

Good.

> > Taking into account that even after the smoothing applied, the other lines are not as straight as they should be, I presume that summing up all lengths the total distance is still pretty correct. You likely could confirm this in case you know the circumference of the buoyo triangle.
> 
> The buoys are never set in exactly the same configuration week to week, but from what I can tell the results after smoothing are quite good. :smile:

I see - please to hear.

**Comment by oalders** [comment]
> Ah, right, I confused the units! Thanks for pointing this out.
> So I've fixed the value of MAX_SENSIBLE_SPEED to be 7 km/h for swimming.

Thanks, @DDvO!
